# Generated by Django 3.0.6 on 2020-05-15 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('associated_entities', models.ManyToManyField(to='api.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_relationship', models.CharField(choices=[('PROVES', 'Proves'), ('SUPPORTS', 'Supports'), ('DISPUTES', 'Disputes'), ('DISPROVES', 'Disproves')], max_length=25)),
                ('verified', models.BooleanField(default=False)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_claim', to='api.Claim')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_source', to='api.Source')),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='evidence',
            field=models.ManyToManyField(blank=True, through='api.ClaimEvidence', to='api.Source'),
        ),
        migrations.AddField(
            model_name='claim',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_claims', to='api.Source'),
        ),
    ]
