# Generated by Django 3.0.6 on 2020-05-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
