# Generated by Django 3.0.6 on 2020-05-15 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200515_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='date_retrieved',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
