# Generated by Django 3.0.6 on 2020-05-18 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20200518_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='experts',
        ),
        migrations.AddField(
            model_name='topic',
            name='experts',
            field=models.ManyToManyField(related_name='expert_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
