# Generated by Django 3.0.6 on 2020-05-18 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20200518_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencereview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
