# Generated by Django 3.0.6 on 2020-05-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_claimevidence_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='associated_entities',
            new_name='authors',
        ),
    ]
