# Generated by Django 3.0.6 on 2020-05-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200515_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_text',
            field=models.CharField(default='Over 100 people have Covid', max_length=200),
            preserve_default=False,
        ),
    ]
