# Generated by Django 3.0.6 on 2020-05-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200518_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Comment'),
        ),
        migrations.AddField(
            model_name='evidencereview',
            name='additional_comments',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
