# Generated by Django 3.0.6 on 2020-05-18 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20200518_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='experts',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
