# Generated by Django 3.0.6 on 2020-05-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200518_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='community_verified',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='expert_verified',
        ),
    ]
