# Generated by Django 3.0.6 on 2020-05-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200515_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimevidence',
            old_name='verified',
            new_name='community_verified',
        ),
        migrations.AddField(
            model_name='claimevidence',
            name='expert_verified',
            field=models.BooleanField(default=False),
        ),
    ]
