# Generated by Django 3.0.6 on 2020-05-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200518_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='source',
            new_name='source_of_claim',
        ),
    ]
