# Generated by Django 3.0.6 on 2020-05-18 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200518_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='source',
            new_name='source_of_evidence',
        ),
    ]
