# Generated by Django 3.0.6 on 2020-05-16 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200515_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClaimEvidence',
            new_name='Evidence',
        ),
    ]
