# Generated by Django 3.0.6 on 2020-05-17 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_trusted_contributor'),
        ('api', '0009_auto_20200516_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_relationship',
            field=models.CharField(choices=[('PROVES', 'Proves'), ('SUPPORTS', 'Supports'), ('UNRELATED', 'Unrelated'), ('INCONCLUSIVE', 'Inconclusive'), ('DISPUTES', 'Disputes'), ('DISPROVES', 'Disproves')], max_length=25),
        ),
        migrations.CreateModel(
            name='EvidenceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduced_evidence_relationship', models.CharField(choices=[('PROVES', 'Proves'), ('SUPPORTS', 'Supports'), ('UNRELATED', 'Unrelated'), ('INCONCLUSIVE', 'Inconclusive'), ('DISPUTES', 'Disputes'), ('DISPROVES', 'Disproves')], max_length=25)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='evidence',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.EvidenceReview'),
        ),
    ]
