# Generated by Django 3.0.6 on 2020-05-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200518_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_degree',
            field=models.CharField(blank=True, choices=[('ORIGINAL', 'Original Research'), ('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary')], max_length=25, null=True),
        ),
    ]
