# Generated by Django 3.0.6 on 2020-05-17 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200517_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_claims', to='api.Source'),
        ),
    ]
