# Generated by Django 3.0.6 on 2020-05-20 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20200520_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='downvoters',
        ),
        migrations.AddField(
            model_name='comment',
            name='downvoters',
            field=models.ManyToManyField(blank=True, null=True, related_name='downvoted_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvoters',
        ),
        migrations.AddField(
            model_name='comment',
            name='upvoters',
            field=models.ManyToManyField(blank=True, null=True, related_name='upvoted_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
