# Generated by Django 3.0.6 on 2020-05-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200520_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='source_of_claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_cited_in', to='api.Source'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='source_of_evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_cited_in', to='api.Source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='authors',
            field=models.ManyToManyField(related_name='sources_authored', to='api.Entity'),
        ),
    ]
