# Generated by Django 3.0.6 on 2020-05-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200520_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
