# Generated by Django 3.0.6 on 2020-05-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_source_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='evidence_relationship',
            field=models.CharField(choices=[('PROVES', 'Proves'), ('SUPPORTS', 'Supports'), ('UNRELATED', 'Unrelated'), ('INCONCLUSIVE', 'Inconclusive'), ('DISPUTES', 'Disputes'), ('DISPROVES', 'Disproves'), ('SPLIT', 'Split')], max_length=25),
        ),
        migrations.AlterField(
            model_name='evidencereview',
            name='deduced_evidence_relationship',
            field=models.CharField(choices=[('PROVES', 'Proves'), ('SUPPORTS', 'Supports'), ('UNRELATED', 'Unrelated'), ('INCONCLUSIVE', 'Inconclusive'), ('DISPUTES', 'Disputes'), ('DISPROVES', 'Disproves'), ('SPLIT', 'Split')], max_length=25),
        ),
    ]
