# Generated by Django 3.0.6 on 2020-05-31 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200525_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='description',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='source',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='source_of_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims_cited_in', to='api.Source'),
        ),
    ]
