# Generated by Django 3.0.6 on 2020-06-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200531_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
