# Generated by Django 3.0.6 on 2020-06-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_evidence_evidence_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='source_of_claim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='claims_cited_in', to='api.Source'),
            preserve_default=False,
        ),
    ]
