# Generated by Django 3.0.7 on 2020-06-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200605_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='short_bio',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
