# Generated by Django 3.0.7 on 2020-06-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200612_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='source_degree',
        ),
    ]
