# Generated by Django 3.0.7 on 2020-06-19 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0024_remove_source_source_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField()),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_invitations', to='api.Evidence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
