# Generated by Django 3.0.7 on 2020-06-26 02:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0026_auto_20200626_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='experts',
            field=models.ManyToManyField(blank=True, related_name='expertise_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
