# Generated by Django 3.0.7 on 2020-08-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200626_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claimants',
            field=models.ManyToManyField(related_name='claims_made', to='api.Entity'),
        ),
    ]
